export const environment = {
    production:false,
    apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYTNiYWFlZi00ZjZiLTQ3ZGYtYTM5Mi1mYmRmNWU1ZTkyN2YiLCJlbWFpbCI6InJhZmFzdGF2YXJlc0BnbWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiVGF2YXJlcyIsIm5iZiI6MTY5NjI3NDM2NywiZXhwIjoxNjk2MzAzMTY3LCJpYXQiOjE2OTYyNzQzNjcsImlzcyI6ImVBZ2VuZGEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0In0.JDokzEkfr9HBmbBzmHGEgjAfp5gn801xUSWjEUtB_kI'
};
